// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Generated by tools/dejavu_l10n.py from the Android app's dejavu_strings.xml. Do not edit; run the script.

import Foundation

extension L10n {
    /// %1$s is based on Firefox, made by Mozilla.
    static func aboutContent(_ p1: String) -> String { tr("dejavu_about_content", "%1$@ is based on Firefox, made by Mozilla.", p1) }
    /// Account
    static var account: String { tr("dejavu_account", "Account") }
    /// Add to essentials
    static var actionAddToEssentials: String { tr("dejavu_action_add_to_essentials", "Add to essentials") }
    /// Bookmark
    static var actionBookmark: String { tr("dejavu_action_bookmark", "Bookmark") }
    /// Change container
    static var actionChangeContainer: String { tr("dejavu_action_change_container", "Change container") }
    /// Close
    static var actionClose: String { tr("dejavu_action_close", "Close") }
    /// Copy link
    static var actionCopyLink: String { tr("dejavu_action_copy_link", "Copy link") }
    /// Delete
    static var actionDelete: String { tr("dejavu_action_delete", "Delete") }
    /// Duplicate
    static var actionDuplicate: String { tr("dejavu_action_duplicate", "Duplicate") }
    /// Move to folder
    static var actionMoveToFolder: String { tr("dejavu_action_move_to_folder", "Move to folder") }
    /// Move to workspace
    static var actionMoveToWorkspace: String { tr("dejavu_action_move_to_workspace", "Move to workspace") }
    /// New folder
    static var actionNewFolder: String { tr("dejavu_action_new_folder", "New folder") }
    /// Pin
    static var actionPin: String { tr("dejavu_action_pin", "Pin") }
    /// Remove from essentials
    static var actionRemoveFromEssentials: String { tr("dejavu_action_remove_from_essentials", "Remove from essentials") }
    /// Rename tab
    static var actionRenameTab: String { tr("dejavu_action_rename_tab", "Rename tab") }
    /// Reset pinned tab
    static var actionResetPin: String { tr("dejavu_action_reset_pin", "Reset pinned tab") }
    /// Share
    static var actionShare: String { tr("dejavu_action_share", "Share") }
    /// Sleep
    static var actionSleep: String { tr("dejavu_action_sleep", "Sleep") }
    /// Split view
    static var actionSplitView: String { tr("dejavu_action_split_view", "Split view") }
    /// Unpin
    static var actionUnpin: String { tr("dejavu_action_unpin", "Unpin") }
    /// Unsplit
    static var actionUnsplit: String { tr("dejavu_action_unsplit", "Unsplit") }
    /// Home
    static var actionsBarHome: String { tr("dejavu_actions_bar_home", "Home") }
    /// Search
    static var actionsBarSearch: String { tr("dejavu_actions_bar_search", "Search") }
    /// New workspace
    static var addWorkspace: String { tr("dejavu_add_workspace", "New workspace") }
    /// %1$d tabs saved to bookmarks
    static func bookmarked(_ p1: Int) -> String { tr("dejavu_bookmarked", "%1$lld tabs saved to bookmarks", p1) }
    /// Bookmarks
    static var bookmarks: String { tr("dejavu_bookmarks", "Bookmarks") }
    /// Cancel
    static var cancel: String { tr("dejavu_cancel", "Cancel") }
    /// Clear
    static var clearUnpinned: String { tr("dejavu_clear_unpinned", "Clear") }
    /// Add container
    static var containerAdd: String { tr("dejavu_container_add", "Add container") }
    /// Banking
    static var containerBanking: String { tr("dejavu_container_banking", "Banking") }
    /// Color
    static var containerColor: String { tr("dejavu_container_color", "Color") }
    /// Close its tabs, pinned tabs included
    static var containerDeleteCloseTabs: String { tr("dejavu_container_delete_close_tabs", "Close its tabs, pinned tabs included") }
    /// Its cookies and site data are deleted. Choose what happens to its tabs.
    static var containerDeleteMessage: String { tr("dejavu_container_delete_message", "Its cookies and site data are deleted. Choose what happens to its tabs.") }
    /// Or move its tabs to
    static var containerDeleteMoveTabs: String { tr("dejavu_container_delete_move_tabs", "Or move its tabs to") }
    /// Delete “%1$s”?
    static func containerDeleteTitle(_ p1: String) -> String { tr("dejavu_container_delete_title", "Delete “%1$@”?", p1) }
    /// Edit container
    static var containerEdit: String { tr("dejavu_container_edit", "Edit container") }
    /// Icon
    static var containerIcon: String { tr("dejavu_container_icon", "Icon") }
    /// Name
    static var containerName: String { tr("dejavu_container_name", "Name") }
    /// Personal
    static var containerPersonal: String { tr("dejavu_container_personal", "Personal") }
    /// Shopping
    static var containerShopping: String { tr("dejavu_container_shopping", "Shopping") }
    /// Work
    static var containerWork: String { tr("dejavu_container_work", "Work") }
    /// Create
    static var create: String { tr("dejavu_create", "Create") }
    /// Custom action
    static var customAction: String { tr("dejavu_custom_action", "Custom action") }
    /// Add action
    static var customActionAdd: String { tr("dejavu_custom_action_add", "Add action") }
    /// Add header
    static var customActionAddHeader: String { tr("dejavu_custom_action_add_header", "Add header") }
    /// Body
    static var customActionBody: String { tr("dejavu_custom_action_body", "Body") }
    /// Examples
    static var customActionExamples: String { tr("dejavu_custom_action_examples", "Examples") }
    /// Tap an example to fill in the fields above. Then put your own server in place of example.com, and your own keys and IDs in place of the parts in capitals.
    static var customActionExamplesHint: String { tr("dejavu_custom_action_examples_hint", "Tap an example to fill in the fields above. Then put your own server in place of example.com, and your own keys and IDs in place of the parts in capitals.") }
    /// Failed: code %1$d (%2$s)
    static func customActionFailedCode(_ p1: Int, _ p2: String) -> String { tr("dejavu_custom_action_failed_code", "Failed: code %1$lld (%2$@)", p1, p2) }
    /// Failed: no answer (%1$s)
    static func customActionFailedNoAnswer(_ p1: String) -> String { tr("dejavu_custom_action_failed_no_answer", "Failed: no answer (%1$@)", p1) }
    /// %1$s, %2$d of %3$d tabs
    static func customActionFailedSome(_ p1: String, _ p2: Int, _ p3: Int) -> String { tr("dejavu_custom_action_failed_some", "%1$@, %2$lld of %3$lld tabs", p1, p2, p3) }
    /// Header
    static var customActionHeaderName: String { tr("dejavu_custom_action_header_name", "Header") }
    /// Value
    static var customActionHeaderValue: String { tr("dejavu_custom_action_header_value", "Value") }
    /// Headers
    static var customActionHeaders: String { tr("dejavu_custom_action_headers", "Headers") }
    /// The request is sent once for every tab the action runs on. Only a 2xx answer counts as success; redirects are not followed and count as failures. Cookies are not sent. Values are URL encoded in the URL and JSON escaped in a JSON body.
    static var customActionHint: String { tr("dejavu_custom_action_hint", "The request is sent once for every tab the action runs on. Only a 2xx answer counts as success; redirects are not followed and count as failures. Cookies are not sent. Values are URL encoded in the URL and JSON escaped in a JSON body.") }
    /// Method
    static var customActionMethod: String { tr("dejavu_custom_action_method", "Method") }
    /// Name
    static var customActionName: String { tr("dejavu_custom_action_name", "Name") }
    /// Remove header
    static var customActionRemoveHeader: String { tr("dejavu_custom_action_remove_header", "Remove header") }
    /// Sent: %1$s
    static func customActionSent(_ p1: String) -> String { tr("dejavu_custom_action_sent", "Sent: %1$@", p1) }
    /// URL
    static var customActionUrl: String { tr("dejavu_custom_action_url", "URL") }
    /// Variables
    static var customActionVariables: String { tr("dejavu_custom_action_variables", "Variables") }
    /// Tap a variable to insert it into the field you are editing.
    static var customActionVariablesHint: String { tr("dejavu_custom_action_variables_hint", "Tap a variable to insert it into the field you are editing.") }
    /// Custom actions
    static var customActions: String { tr("dejavu_custom_actions", "Custom actions") }
    /// Delete
    static var delete: String { tr("dejavu_delete", "Delete") }
    /// Delete “%1$s”?
    static func deleteItemTitle(_ p1: String) -> String { tr("dejavu_delete_item_title", "Delete “%1$@”?", p1) }
    /// Pinned tabs, essentials and folders with everything inside them are removed, and their open tabs are closed.
    static var deleteItemsMessage: String { tr("dejavu_delete_items_message", "Pinned tabs, essentials and folders with everything inside them are removed, and their open tabs are closed.") }
    /// Delete %1$d items?
    static func deleteItemsTitle(_ p1: Int) -> String { tr("dejavu_delete_items_title", "Delete %1$lld items?", p1) }
    /// Downloads
    static var downloads: String { tr("dejavu_downloads", "Downloads") }
    /// Drop here to add to essentials
    static var essentialsDrop: String { tr("dejavu_essentials_drop", "Drop here to add to essentials") }
    /// Essentials hold up to %1$d tabs
    static func essentialsFull(_ p1: Int) -> String { tr("dejavu_essentials_full", "Essentials hold up to %1$lld tabs", p1) }
    /// Essentials per container
    static var essentialsPerContainer: String { tr("dejavu_essentials_per_container", "Essentials per container") }
    /// Each container keeps its own essentials. A workspace shows the essentials of its default container.
    static var essentialsPerContainerSummary: String { tr("dejavu_essentials_per_container_summary", "Each container keeps its own essentials. A workspace shows the essentials of its default container.") }
    /// Start an automation with the page
    static var exampleAutomation: String { tr("dejavu_example_automation", "Start an automation with the page") }
    /// Save the page as a bookmark
    static var exampleBookmark: String { tr("dejavu_example_bookmark", "Save the page as a bookmark") }
    /// Post the page to a chat
    static var exampleChat: String { tr("dejavu_example_chat", "Post the page to a chat") }
    /// Save the page as a note
    static var exampleNote: String { tr("dejavu_example_note", "Save the page as a note") }
    /// Send the page as a notification
    static var exampleNotification: String { tr("dejavu_example_notification", "Send the page as a notification") }
    /// Save the page to read later
    static var exampleReadLater: String { tr("dejavu_example_read_later", "Save the page to read later") }
    /// Send every variable as JSON, for n8n, Node-RED and similar tools
    static var exampleWebhook: String { tr("dejavu_example_webhook", "Send every variable as JSON, for n8n, Node-RED and similar tools") }
    /// Extensions
    static var extensions: String { tr("dejavu_extensions", "Extensions") }
    /// Container
    static var externalLinksContainer: String { tr("dejavu_external_links_container", "Container") }
    /// Links you open from other apps start in this workspace and container. Back takes you back to the app.
    static var externalLinksHint: String { tr("dejavu_external_links_hint", "Links you open from other apps start in this workspace and container. Back takes you back to the app.") }
    /// The workspace shown last
    static var externalLinksLastWorkspace: String { tr("dejavu_external_links_last_workspace", "The workspace shown last") }
    /// Open in a private tab
    static var externalLinksPrivate: String { tr("dejavu_external_links_private", "Open in a private tab") }
    /// Links from other apps open in the private workspace, without a container.
    static var externalLinksPrivateSummary: String { tr("dejavu_external_links_private_summary", "Links from other apps open in the private workspace, without a container.") }
    /// Workspace
    static var externalLinksWorkspace: String { tr("dejavu_external_links_workspace", "Workspace") }
    /// The default container of the workspace
    static var externalLinksWorkspaceContainer: String { tr("dejavu_external_links_workspace_container", "The default container of the workspace") }
    /// New subfolder
    static var folderNewSubfolder: String { tr("dejavu_folder_new_subfolder", "New subfolder") }
    /// Rename folder
    static var folderRename: String { tr("dejavu_folder_rename", "Rename folder") }
    /// Pinned tabs, no folder
    static var folderTopLevel: String { tr("dejavu_folder_top_level", "Pinned tabs, no folder") }
    /// Unpack folder
    static var folderUnpack: String { tr("dejavu_folder_unpack", "Unpack folder") }
    /// History
    static var history: String { tr("dejavu_history", "History") }
    /// Open in container
    static var linkOpenInContainer: String { tr("dejavu_link_open_in_container", "Open in container") }
    /// Open in split view
    static var linkOpenInSplitView: String { tr("dejavu_link_open_in_split_view", "Open in split view") }
    /// Open in workspace
    static var linkOpenInWorkspace: String { tr("dejavu_link_open_in_workspace", "Open in workspace") }
    /// Opened in %1$s
    static func linkOpenedIn(_ p1: String) -> String { tr("dejavu_link_opened_in", "Opened in %1$@", p1) }
    /// %1$d links copied
    static func linksCopied(_ p1: Int) -> String { tr("dejavu_links_copied", "%1$lld links copied", p1) }
    /// Back
    static var menuBack: String { tr("dejavu_menu_back", "Back") }
    /// Bookmark
    static var menuBookmarkPage: String { tr("dejavu_menu_bookmark_page", "Bookmark") }
    /// Bookmarks
    static var menuBookmarks: String { tr("dejavu_menu_bookmarks", "Bookmarks") }
    /// Desktop site
    static var menuDesktopSite: String { tr("dejavu_menu_desktop_site", "Desktop site") }
    /// Downloads
    static var menuDownloads: String { tr("dejavu_menu_downloads", "Downloads") }
    /// Edit
    static var menuEdit: String { tr("dejavu_menu_edit", "Edit") }
    /// Edit bookmark
    static var menuEditBookmark: String { tr("dejavu_menu_edit_bookmark", "Edit bookmark") }
    /// Add to essentials
    static var menuEssentialTab: String { tr("dejavu_menu_essential_tab", "Add to essentials") }
    /// Extensions
    static var menuExtensions: String { tr("dejavu_menu_extensions", "Extensions") }
    /// Find in page
    static var menuFindInPage: String { tr("dejavu_menu_find_in_page", "Find in page") }
    /// Forward
    static var menuForward: String { tr("dejavu_menu_forward", "Forward") }
    /// History
    static var menuHistory: String { tr("dejavu_menu_history", "History") }
    /// Manage extensions
    static var menuManageExtensions: String { tr("dejavu_menu_manage_extensions", "Manage extensions") }
    /// Open in app
    static var menuOpenInApp: String { tr("dejavu_menu_open_in_app", "Open in app") }
    /// Passwords
    static var menuPasswords: String { tr("dejavu_menu_passwords", "Passwords") }
    /// Pin tab
    static var menuPinTab: String { tr("dejavu_menu_pin_tab", "Pin tab") }
    /// Print
    static var menuPrint: String { tr("dejavu_menu_print", "Print") }
    /// Reload
    static var menuRefresh: String { tr("dejavu_menu_refresh", "Reload") }
    /// Remove essential
    static var menuRemoveEssential: String { tr("dejavu_menu_remove_essential", "Remove essential") }
    /// Pin this URL
    static var menuReplacePinnedUrl: String { tr("dejavu_menu_replace_pinned_url", "Pin this URL") }
    /// Report site issue
    static var menuReportBrokenSite: String { tr("dejavu_menu_report_broken_site", "Report site issue") }
    /// Reset to pinned URL
    static var menuResetPinnedUrl: String { tr("dejavu_menu_reset_pinned_url", "Reset to pinned URL") }
    /// Save as PDF
    static var menuSaveAsPdf: String { tr("dejavu_menu_save_as_pdf", "Save as PDF") }
    /// Settings
    static var menuSettings: String { tr("dejavu_menu_settings", "Settings") }
    /// Share
    static var menuShare: String { tr("dejavu_menu_share", "Share") }
    /// There are no other tabs in this workspace.
    static var menuSplitNoTabs: String { tr("dejavu_menu_split_no_tabs", "There are no other tabs in this workspace.") }
    /// Split view
    static var menuSplitView: String { tr("dejavu_menu_split_view", "Split view") }
    /// Split view with
    static var menuSplitWith: String { tr("dejavu_menu_split_with", "Split view with") }
    /// Stop
    static var menuStop: String { tr("dejavu_menu_stop", "Stop") }
    /// Summarize
    static var menuSummarize: String { tr("dejavu_menu_summarize", "Summarize") }
    /// Translate
    static var menuTranslate: String { tr("dejavu_menu_translate", "Translate") }
    /// Unpin tab
    static var menuUnpinTab: String { tr("dejavu_menu_unpin_tab", "Unpin tab") }
    /// Unsplit
    static var menuUnsplit: String { tr("dejavu_menu_unsplit", "Unsplit") }
    /// Add a button
    static var moreMenuAddItem: String { tr("dejavu_more_menu_add_item", "Add a button") }
    /// Add a row
    static var moreMenuAddRow: String { tr("dejavu_more_menu_add_row", "Add a row") }
    /// Every button is already in the menu.
    static var moreMenuAllAdded: String { tr("dejavu_more_menu_all_added", "Every button is already in the menu.") }
    /// Delete row
    static var moreMenuDeleteRow: String { tr("dejavu_more_menu_delete_row", "Delete row") }
    /// Hide edit button
    static var moreMenuHideEdit: String { tr("dejavu_more_menu_hide_edit", "Hide edit button") }
    /// The button below the menu that opens this screen
    static var moreMenuHideEditSummary: String { tr("dejavu_more_menu_hide_edit_summary", "The button below the menu that opens this screen") }
    /// The first row is the actions bar below pages. Swipe the actions bar up, or the address bar down, to open the whole menu. Tap a button to move or remove it. Extensions always take a whole row.
    static var moreMenuHint: String { tr("dejavu_more_menu_hint", "The first row is the actions bar below pages. Swipe the actions bar up, or the address bar down, to open the whole menu. Tap a button to move or remove it. Extensions always take a whole row.") }
    /// Move down
    static var moreMenuMoveDown: String { tr("dejavu_more_menu_move_down", "Move down") }
    /// Move left
    static var moreMenuMoveLeft: String { tr("dejavu_more_menu_move_left", "Move left") }
    /// Move right
    static var moreMenuMoveRight: String { tr("dejavu_more_menu_move_right", "Move right") }
    /// Move up
    static var moreMenuMoveUp: String { tr("dejavu_more_menu_move_up", "Move up") }
    /// Preview
    static var moreMenuPreview: String { tr("dejavu_more_menu_preview", "Preview") }
    /// Remove
    static var moreMenuRemove: String { tr("dejavu_more_menu_remove", "Remove") }
    /// Reset to default
    static var moreMenuReset: String { tr("dejavu_more_menu_reset", "Reset to default") }
    /// Row %1$d
    static func moreMenuRow(_ p1: Int) -> String { tr("dejavu_more_menu_row", "Row %1$lld", p1) }
    /// This row is full.
    static var moreMenuRowFull: String { tr("dejavu_more_menu_row_full", "This row is full.") }
    /// New private tab
    static var newPrivateTab: String { tr("dejavu_new_private_tab", "New private tab") }
    /// New Tab
    static var newTab: String { tr("dejavu_new_tab", "New Tab") }
    /// New tab in a container
    static var newTabInContainer: String { tr("dejavu_new_tab_in_container", "New tab in a container") }
    /// New tab without container
    static var newTabNoContainer: String { tr("dejavu_new_tab_no_container", "New tab without container") }
    /// New tab in a temporary container
    static var newTabTemporaryContainer: String { tr("dejavu_new_tab_temporary_container", "New tab in a temporary container") }
    /// New temporary container
    static var newTemporaryContainer: String { tr("dejavu_new_temporary_container", "New temporary container") }
    /// Temporary containers in use
    static var openTemporaryContainers: String { tr("dejavu_open_temporary_containers", "Temporary containers in use") }
    /// Close unpinned tabs
    static var preferencesCloseUnpinnedTabs: String { tr("dejavu_preferences_close_unpinned_tabs", "Close unpinned tabs") }
    /// Close all
    static var privateCloseAll: String { tr("dejavu_private_close_all", "Close all") }
    /// Private
    static var privateWorkspace: String { tr("dejavu_private_workspace", "Private") }
    /// Title, empty for the page title
    static var renameTabHint: String { tr("dejavu_rename_tab_hint", "Title, empty for the page title") }
    /// Save
    static var save: String { tr("dejavu_save", "Save") }
    /// Search or enter address
    static var searchHint: String { tr("dejavu_search_hint", "Search or enter address") }
    /// %1$d selected
    static func selectionCount(_ p1: Int) -> String { tr("dejavu_selection_count", "%1$lld selected", p1) }
    /// Exit selection
    static var selectionExit: String { tr("dejavu_selection_exit", "Exit selection") }
    /// Select all
    static var selectionSelectAll: String { tr("dejavu_selection_select_all", "Select all") }
    /// Settings
    static var settings: String { tr("dejavu_settings", "Settings") }
    /// Actions
    static var settingsActions: String { tr("dejavu_settings_actions", "Actions") }
    /// Actions bar
    static var settingsActionsBar: String { tr("dejavu_settings_actions_bar", "Actions bar") }
    /// All actions
    static var settingsAllActions: String { tr("dejavu_settings_all_actions", "All actions") }
    /// Choose the actions shown at the bottom of the home page when you long-press to select tabs, essentials or folders. An action only shows up when it can run on what is selected.
    static var settingsAllActionsHint: String { tr("dejavu_settings_all_actions_hint", "Choose the actions shown at the bottom of the home page when you long-press to select tabs, essentials or folders. An action only shows up when it can run on what is selected.") }
    /// %1$d of %2$d shown when you select tabs
    static func settingsAllActionsSummary(_ p1: Int, _ p2: Int) -> String { tr("dejavu_settings_all_actions_summary", "%1$lld of %2$lld shown when you select tabs", p1, p2) }
    /// Buttons
    static var settingsButtons: String { tr("dejavu_settings_buttons", "Buttons") }
    /// Containers
    static var settingsContainers: String { tr("dejavu_settings_containers", "Containers") }
    /// Add, edit and delete containers
    static var settingsContainersEntrySummary: String { tr("dejavu_settings_containers_entry_summary", "Add, edit and delete containers") }
    /// Tabs in a container keep their own cookies and site data. Long-press New Tab on the home page to open a tab in a container, or give a whole workspace a container from its menu.
    static var settingsContainersHint: String { tr("dejavu_settings_containers_hint", "Tabs in a container keep their own cookies and site data. Long-press New Tab on the home page to open a tab in a container, or give a whole workspace a container from its menu.") }
    /// Links from other apps
    static var settingsExternalLinks: String { tr("dejavu_settings_external_links", "Links from other apps") }
    /// Workspace and container they open in
    static var settingsExternalLinksSummary: String { tr("dejavu_settings_external_links_summary", "Workspace and container they open in") }
    /// More menu
    static var settingsMoreMenu: String { tr("dejavu_settings_more_menu", "More menu") }
    /// The actions bar below pages and the menu it opens
    static var settingsMoreMenuSummary: String { tr("dejavu_settings_more_menu_summary", "The actions bar below pages and the menu it opens") }
    /// No buttons
    static var settingsNoButtons: String { tr("dejavu_settings_no_buttons", "No buttons") }
    /// Choose up to %1$d buttons for pinned tab rows.
    static func settingsPinnedActionsHint(_ p1: Int) -> String { tr("dejavu_settings_pinned_actions_hint", "Choose up to %1$lld buttons for pinned tab rows.", p1) }
    /// Pinned tabs
    static var settingsPinnedTabs: String { tr("dejavu_settings_pinned_tabs", "Pinned tabs") }
    /// Sync with Zen
    static var settingsSync: String { tr("dejavu_settings_sync", "Sync with Zen") }
    /// Workspaces, containers, pinned tabs and essentials
    static var settingsSyncSummary: String { tr("dejavu_settings_sync_summary", "Workspaces, containers, pinned tabs and essentials") }
    /// Tab actions
    static var settingsTabActions: String { tr("dejavu_settings_tab_actions", "Tab actions") }
    /// Buttons on tabs, and actions for selected tabs
    static var settingsTabActionsEntrySummary: String { tr("dejavu_settings_tab_actions_entry_summary", "Buttons on tabs, and actions for selected tabs") }
    /// Choose the buttons of pinned and unpinned tab rows, and the actions shown when you select tabs. Actions you add yourself can be used in all three.
    static var settingsTabActionsHint: String { tr("dejavu_settings_tab_actions_hint", "Choose the buttons of pinned and unpinned tab rows, and the actions shown when you select tabs. Actions you add yourself can be used in all three.") }
    /// Dejavu
    static var settingsTitle: String { tr("dejavu_settings_title", "Dejavu") }
    /// Choose up to %1$d buttons for unpinned tab rows.
    static func settingsUnpinnedActionsHint(_ p1: Int) -> String { tr("dejavu_settings_unpinned_actions_hint", "Choose up to %1$lld buttons for unpinned tab rows.", p1) }
    /// Unpinned tabs
    static var settingsUnpinnedTabs: String { tr("dejavu_settings_unpinned_tabs", "Unpinned tabs") }
    /// Close split view
    static var splitClose: String { tr("dejavu_split_close", "Close split view") }
    /// Show on top
    static var splitShowOnTop: String { tr("dejavu_split_show_on_top", "Show on top") }
    /// Split view
    static var splitView: String { tr("dejavu_split_view", "Split view") }
    /// Sync workspaces
    static var syncEnabled: String { tr("dejavu_sync_enabled", "Sync workspaces") }
    /// Keeps your workspaces with their colors and icons, containers, pinned tabs, essentials and folders the same as in Zen Browser on your computer and in Dejavu on your other devices. It uses the Mozilla account you sync Firefox data with.
    static var syncHint: String { tr("dejavu_sync_hint", "Keeps your workspaces with their colors and icons, containers, pinned tabs, essentials and folders the same as in Zen Browser on your computer and in Dejavu on your other devices. It uses the Mozilla account you sync Firefox data with.") }
    /// Last synced %1$s
    static func syncLastSynced(_ p1: String) -> String { tr("dejavu_sync_last_synced", "Last synced %1$@", p1) }
    /// Not synced yet
    static var syncNeverSynced: String { tr("dejavu_sync_never_synced", "Not synced yet") }
    /// Include unpinned tabs
    static var syncNormalTabs: String { tr("dejavu_sync_normal_tabs", "Include unpinned tabs") }
    /// Also sync the other tabs of each workspace, not just pinned tabs and folders. Zen syncs them when its own Include unpinned tabs option is on.
    static var syncNormalTabsSummary: String { tr("dejavu_sync_normal_tabs_summary", "Also sync the other tabs of each workspace, not just pinned tabs and folders. Zen syncs them when its own Include unpinned tabs option is on.") }
    /// Sync now
    static var syncNow: String { tr("dejavu_sync_now", "Sync now") }
    /// Sync is off on this device
    static var syncOff: String { tr("dejavu_sync_off", "Sync is off on this device") }
    /// Another device uses a newer version of spaces sync. Update Dejavu to keep syncing.
    static var syncProblemNeedsUpdate: String { tr("dejavu_sync_problem_needs_update", "Another device uses a newer version of spaces sync. Update Dejavu to keep syncing.") }
    /// Waiting for Firefox Sync to finish setting up your account.
    static var syncProblemNotSetUp: String { tr("dejavu_sync_problem_not_set_up", "Waiting for Firefox Sync to finish setting up your account.") }
    /// Spaces sync is off for your Mozilla account. Turn it on here or in Zen’s sync settings. Turning it on here also turns it on in Zen.
    static var syncProblemNotTurnedOn: String { tr("dejavu_sync_problem_not_turned_on", "Spaces sync is off for your Mozilla account. Turn it on here or in Zen’s sync settings. Turning it on here also turns it on in Zen.") }
    /// Could not reach the sync servers. Dejavu will try again.
    static var syncProblemOffline: String { tr("dejavu_sync_problem_offline", "Could not reach the sync servers. Dejavu will try again.") }
    /// The sync servers had a problem. Dejavu will try again.
    static var syncProblemServer: String { tr("dejavu_sync_problem_server", "The sync servers had a problem. Dejavu will try again.") }
    /// Sign in to your Mozilla account again to keep syncing.
    static var syncProblemSignIn: String { tr("dejavu_sync_problem_sign_in", "Sign in to your Mozilla account again to keep syncing.") }
    /// Sign in
    static var syncSignIn: String { tr("dejavu_sync_sign_in", "Sign in") }
    /// Sign in to your Mozilla account to sync your workspaces with Zen.
    static var syncSignedOut: String { tr("dejavu_sync_signed_out", "Sign in to your Mozilla account to sync your workspaces with Zen.") }
    /// Syncing…
    static var syncSyncing: String { tr("dejavu_sync_syncing", "Syncing…") }
    /// Turn on spaces sync
    static var syncTurnOn: String { tr("dejavu_sync_turn_on", "Turn on spaces sync") }
    /// In Zen, open Settings, then Sync, and turn on sidebar sync. Tabs that are not pinned are not synced.
    static var syncZenHint: String { tr("dejavu_sync_zen_hint", "In Zen, open Settings, then Sync, and turn on sidebar sync. Tabs that are not pinned are not synced.") }
    /// %1$d tabs closed
    static func tabsClosed(_ p1: Int) -> String { tr("dejavu_tabs_closed", "%1$lld tabs closed", p1) }
    /// Temporary containers by default
    static var temporaryByDefault: String { tr("dejavu_temporary_by_default", "Temporary containers by default") }
    /// In workspaces without a default container, every new tab opens in its own temporary container. A temporary container and its cookies are deleted when its last tab closes.
    static var temporaryByDefaultSummary: String { tr("dejavu_temporary_by_default_summary", "In workspaces without a default container, every new tab opens in its own temporary container. A temporary container and its cookies are deleted when its last tab closes.") }
    /// Temporary container
    static var temporaryContainer: String { tr("dejavu_temporary_container", "Temporary container") }
    /// Container: %1$s
    static func toolbarContainer(_ p1: String) -> String { tr("dejavu_toolbar_container", "Container: %1$@", p1) }
    /// Undo
    static var undo: String { tr("dejavu_undo", "Undo") }
    /// Default container
    static var workspaceContainer: String { tr("dejavu_workspace_container", "Default container") }
    /// New tabs of this workspace open in this container.
    static var workspaceContainerHint: String { tr("dejavu_workspace_container_hint", "New tabs of this workspace open in this container.") }
    /// Home
    static var workspaceDefaultName: String { tr("dejavu_workspace_default_name", "Home") }
    /// Delete workspace
    static var workspaceDelete: String { tr("dejavu_workspace_delete", "Delete workspace") }
    /// Its tabs, pinned tabs and folders move to the neighbouring workspace.
    static var workspaceDeleteMessage: String { tr("dejavu_workspace_delete_message", "Its tabs, pinned tabs and folders move to the neighbouring workspace.") }
    /// Delete “%1$s”?
    static func workspaceDeleteTitle(_ p1: String) -> String { tr("dejavu_workspace_delete_title", "Delete “%1$@”?", p1) }
    /// Edit workspace
    static var workspaceEdit: String { tr("dejavu_workspace_edit", "Edit workspace") }
    /// Icon
    static var workspaceIcon: String { tr("dejavu_workspace_icon", "Icon") }
    /// Workspace menu
    static var workspaceMenu: String { tr("dejavu_workspace_menu", "Workspace menu") }
    /// Move left
    static var workspaceMoveLeft: String { tr("dejavu_workspace_move_left", "Move left") }
    /// Move right
    static var workspaceMoveRight: String { tr("dejavu_workspace_move_right", "Move right") }
    /// Name
    static var workspaceName: String { tr("dejavu_workspace_name", "Name") }
    /// No container
    static var workspaceNoContainer: String { tr("dejavu_workspace_no_container", "No container") }
    /// Theme
    static var workspaceTheme: String { tr("dejavu_workspace_theme", "Theme") }
    /// Grain
    static var workspaceThemeGrain: String { tr("dejavu_workspace_theme_grain", "Grain") }
    /// Intensity
    static var workspaceThemeIntensity: String { tr("dejavu_workspace_theme_intensity", "Intensity") }
}
